@baseUrl = http://localhost:3002

### 1. Registro de usuario
POST {{baseUrl}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Luis",
  "email": "luisferrer2002@gmail.com",
  "password": "Password123"
}

###
@tokenFromRegister = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBlYTVjMzQyMzlkYjI3OTk0OGU1N2YiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTc5MDQwMywiZXhwIjoxNzQ1ODc2ODAzfQ.WW8RkZcFiBARHF9w9LZfah0ObOKozxxSNIG61sTqMrM

### 2. Validación de email (Código de verificación)
POST {{baseUrl}}/api/users/validate-email HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenFromRegister}}

{
  "code": "968217"
}

### 3. Login de usuario
POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "luisferrer2002@gmail.com",
  "password": "NewPassword123"
}

###
@tokenFromLogin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBlYTVjMzQyMzlkYjI3OTk0OGU1N2YiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTc5MDc1NywiZXhwIjoxNzQ1ODc3MTU3fQ.HUHwfiAByeFt24V2pDUTBj-jkMjJpG146hRs5D6gkwQ
@userId = 680ea5c34239db279948e57f

