@baseUrl = http://localhost:3002

### 1. Registro de usuario
POST {{baseUrl}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Luis",
  "age": 25,
  "email": "luisferrer2002@gmail.com",
  "password": "Password123"
}

###
@tokenFromRegister = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBhNjZhMDU2NDI4MWZiZDcyNmQzMGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTUxMjA5NiwiZXhwIjoxNzQ1NTk4NDk2fQ.WIF_8clVH8CA55Mmaf8SzgRyV5zvhGtccjevfbjdiss

### 2. Validación de email (Código de verificación)
POST {{baseUrl}}/api/users/validate-email HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenFromRegister}}

{
  "code": "560464"
}

### 3. Login de usuario
POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "luisferrer2002@gmail.com",
  "password": "Password123"
}

###
@tokenFromLogin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODA3YmUzN2VmZDk5ODdmOGUyZGExYjkiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTU2OTUyNywiZXhwIjoxNzQ1NjU1OTI3fQ.IeDQ6seqKtofyIJTPF-3ubWop2OEmRD0fK6pMcP48DM
@userId = 6807be37efd9987f8e2da1b9

