@baseUrl = http://localhost:3002
@tokenFromLogin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBlYTVjMzQyMzlkYjI3OTk0OGU1N2YiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDU5MzE0MzgsImV4cCI6MTc0NjAxNzgzOH0.n6PCYgcWsZ_oesZFjMVuAftxc95GQp4UH6xRjkM_BD0
@userId = 680ea5c34239db279948e57f

@clientId = 680ec2c65cbb6f2528f1eb4f

@projectId = 680ec3ce5cbb6f2528f1eb5c

@deliveryNoteId = 680ec4625cbb6f2528f1eb6b



### 1. Crear albarán

POST http://localhost:3002/api/deliveryNote
Content-Type: application/json
Authorization: Bearer {{tokenFromLogin}}

{
  "clientId": "{{clientId}}",
  "projectId": "{{projectId}}",
  "items": [
    {
      "type": "hour",
      "description": "Revisión sistema calefaccion",
      "quantity": 4
    },
    {
      "type": "material",
      "description": "Cableado Cat6",
      "quantity": 2
    }
  ]
}

### 2. Obtener lista de albaranes
GET http://localhost:3002/api/deliverynote
Authorization: Bearer {{tokenFromLogin}}

### 3. Obtener albarán por ID
GET http://localhost:3002/api/deliverynote/{{deliveryNoteId}}
Authorization: Bearer {{tokenFromLogin}}

### 4. Generar PDF de un albarán
GET http://localhost:3002/api/deliverynote/pdf/{{deliveryNoteId}}
Authorization: Bearer {{tokenFromLogin}}

### 5. Actualizar un albarán (solo si no está firmado)
PUT {{baseUrl}}/api/deliverynote/{{deliveryNoteId}}
Authorization: Bearer {{tokenFromLogin}}
Content-Type: application/json

{
  "items": [
    { "type": "hour", "description": "Horas modificadas", "quantity": 3 },
    { "type": "material", "description": "Nuevo material", "quantity": 20 }
  ]
}

### 6. Firmar un albarán (subida de imagen)
POST {{baseUrl}}/api/deliverynote/sign/{{deliveryNoteId}}
Authorization: Bearer {{tokenFromLogin}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="firma.png"
Content-Type: image/png

< ./firma.png
--MyBoundary--

