### 🔐 Login
POST http://localhost:3002/api/auth/login
Content-Type: application/json

{
  "email": "luisferrer2002@gmail.com",
  "password": "Password123"
}

### ✍️ Firmar albarán
# ⚠️ Sustituye el token y el ID del albarán antes de ejecutar
POST http://localhost:3002/api/deliverynote/sign/661f2010c1c63f34d6a44444
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODA3YmUzN2VmZDk5ODdmOGUyZGExYjkiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTMzOTM1NywiZXhwIjoxNzQ1NDI1NzU3fQ.-NvY3PFmGfdjLx7Yvxili8d_5BTXy0IIrXF_4onIFGA

Content-Disposition: form-data; name="image"; filename="firma.png"
Content-Type: image/png

< ./firma.png
