@baseUrl = http://localhost:3002

### 1. Registro de usuario
POST {{baseUrl}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Luis",
  "age": 25,
  "email": "luisferrer2002@gmail.com",
  "password": "Password123"
}

###
@tokenFromRegister = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBhNjZhMDU2NDI4MWZiZDcyNmQzMGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTUxMjA5NiwiZXhwIjoxNzQ1NTk4NDk2fQ.WIF_8clVH8CA55Mmaf8SzgRyV5zvhGtccjevfbjdiss

### 2. Validación de email (Código de verificación)
POST {{baseUrl}}/api/users/validate-email HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenFromRegister}}

{
  "code": "560464"
}

### 3. Login de usuario
POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "luisferrer2002@gmail.com",
  "password": "Password123"
}

###
@tokenFromLogin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBhNjZhMDU2NDI4MWZiZDcyNmQzMGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTUxMjIyMywiZXhwIjoxNzQ1NTk4NjIzfQ.baOcwWs5o8IAZiaTnNPoBJL-9CmPfG3yi_umkVP6dR0
@userId = 680a66a0564281fbd726d30b

### ✅ Crear albarán
POST http://localhost:3002/api/deliveryNote
Content-Type: application/json
Authorization: Bearer {{tokenFromLogin}}

{
  "clientId": "661f1f00c1c63f34d6a22222",
  "projectId": "661f1f99c1c63f34d6a33333",
  "items": [
    {
      "type": "hour",
      "description": "Revisión sistema eléctrico",
      "quantity": 4
    },
    {
      "type": "material",
      "description": "Cableado Cat6",
      "quantity": 2
    }
  ]
}

###

### 📥 Obtener lista de albaranes
GET http://localhost:3002/api/deliverynote
Authorization: Bearer {{tokenFromLogin}}

###

### 📄 Generar PDF de un albarán
GET http://localhost:3002/api/deliverynote/pdf/680a676e564281fbd726d310
Authorization: Bearer {{tokenFromLogin}}

###

### ✍️ Firmar albarán
POST http://localhost:3002/api/deliverynote/sign/680a676e564281fbd726d310
Authorization: Bearer {{tokenFromLogin}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="firma.png"
Content-Type: image/png

< ./firma.png
--boundary--

