@baseUrl = http://localhost:3002
@tokenFromLogin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODA3YmUzN2VmZDk5ODdmOGUyZGExYjkiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTU2OTUyNywiZXhwIjoxNzQ1NjU1OTI3fQ.IeDQ6seqKtofyIJTPF-3ubWop2OEmRD0fK6pMcP48DM
@userId = 6807be37efd9987f8e2da1b9

###

GET {{baseUrl}}/api/users/me
Authorization: Bearer {{tokenFromLogin}}

###

DELETE {{baseUrl}}/api/users/me
Authorization: Bearer {{tokenFromLogin}}

###

DELETE {{baseUrl}}/api/users/me?soft=false
Authorization: Bearer {{tokenFromLogin}}

###

PATCH {{baseUrl}}/api/users/logo
Authorization: Bearer {{tokenFromLogin}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="firma.png"
Content-Type: image/png

< ./firma.png
--MyBoundary--

###

GET {{baseUrl}}/api/users
Authorization: Bearer {{tokenFromLogin}}

###

GET {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{tokenFromLogin}}

###

PATCH {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{tokenFromLogin}}
Content-Type: application/json

{
  "name": "Luis Actualizado"
}

###

DELETE {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{tokenFromLogin}}

###

PATCH {{baseUrl}}/api/users/role/{{userId}}
Authorization: Bearer {{tokenFromLogin}}
Content-Type: application/json

{
  "role": "admin"
}


###

PATCH {{baseUrl}}/api/users/onboarding/personal
Authorization: Bearer {{tokenFromLogin}}
Content-Type: application/json

{
  "name": "Luis",
  "lastName": "Ferrer",
  "nif": "12345678Z"
}

###

PATCH {{baseUrl}}/api/users/onboarding/company
Authorization: Bearer {{tokenFromLogin}}
Content-Type: application/json

{
  "companyName": "Mi Empresa",
  "cif": "B12345678",
  "address": "Calle Falsa 123"
}

###

POST {{baseUrl}}/api/users/recover-password-code
Content-Type: application/json

{
  "email": "luisferrer2002@gmail.com",
  "currentPassword": "Password123"
}

###

POST {{baseUrl}}/api/users/change-password
Content-Type: application/json

{
  "email": "luisferrer2002@gmail.com",
  "recoveryCode": "335940",
  "newPassword": "NewPassword123"
}

###

POST {{baseUrl}}/api/users/invite
Authorization: Bearer {{tokenFromLogin}}
Content-Type: application/json

{
  "email": "nuevoinvitado@example.com"
}
